// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function DeleteRun(arg1) {
  return window['go']['main']['App']['DeleteRun'](arg1);
}

export function ListRequests() {
  return window['go']['main']['App']['ListRequests']();
}

export function ListRuns() {
  return window['go']['main']['App']['ListRuns']();
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveRun(arg1) {
  return window['go']['main']['App']['SaveRun'](arg1);
}

export function SendSample(arg1) {
  return window['go']['main']['App']['SendSample'](arg1);
}

export function StartTest(arg1) {
  return window['go']['main']['App']['StartTest'](arg1);
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}
