// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {engine} from '../models';

export function DeleteFlow(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteRun(arg1:string):Promise<void>;

export function ImportRun(arg1:string,arg2:string):Promise<model.SavedRun>;

export function ListFlows():Promise<Array<main.SavedFlow>>;

export function ListRequests():Promise<Array<main.SavedRequest>>;

export function ListRuns():Promise<Array<model.SavedRun>>;

export function SaveFlow(arg1:main.SavedFlow):Promise<main.SavedFlow>;

export function SaveRequest(arg1:main.SavedRequest):Promise<main.SavedRequest>;

export function SaveRun(arg1:model.SavedRun):Promise<model.SavedRun>;

export function SendSample(arg1:main.SavedRequest):Promise<main.SampleResponse>;

export function StartTest(arg1:engine.Config):Promise<void>;

export function StopTest():Promise<void>;
