// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteRun(arg1:string):Promise<void>;

export function ImportRun(arg1:string,arg2:string):Promise<main.SavedRun>;

export function ListRequests():Promise<Array<main.SavedRequest>>;

export function ListRuns():Promise<Array<main.SavedRun>>;

export function SaveRequest(arg1:main.SavedRequest):Promise<main.SavedRequest>;

export function SaveRun(arg1:main.SavedRun):Promise<main.SavedRun>;

export function SendSample(arg1:main.SavedRequest):Promise<main.SampleResponse>;

export function StartTest(arg1:engine.Config):Promise<void>;

export function StopTest():Promise<void>;
